name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Build Release x64
        run: msbuild ReFsBlockCloneGUI.sln /p:Configuration=Release /p:Platform=x64 /p:PreferredToolArchitecture=x64 /m
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: src/x64/Release/ReFsBlockCloneGUI.exe
          generate_release_notes: true
      - name: Cleanup Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2.1.0
        if: always()
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
